FROM node:16-alpine AS deps
RUN apk add --no-cache libc6-compat

COPY package.json package.json
COPY yarn.lock yarn.lock
COPY newrelic.js newrelic.js
COPY .nuxt/ .nuxt/
COPY node_modules/ node_modules/

EXPOSE 4949

CMD yarn start