version: '3.3'
services:
  app:
    build:
      context: "."
      dockerfile: Dockerfile.prod
    environment:
      HOST: 0.0.0.0
      PORT: 4949
      NEW_RELIC_APP_NAME: Nuxtolio
    ports:
      - 4949:4949
